# Generated by Django 3.1.5 on 2021-02-22 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('details', models.TextField(blank=True, max_length=1000, verbose_name='Details')),
                ('severity', models.IntegerField(choices=[(5, 'Blocker'), (4, 'Critical'), (3, 'Major'), (2, 'Minor'), (1, 'Trivial'), (-1, 'Not Categorized')], default=-1, null=True, verbose_name='Severity')),
                ('issue_type', models.CharField(choices=[('IMP', 'Improvement'), ('NEW', 'New Feature'), ('BUG', 'Bug'), ('TST', 'Test'), ('TSK', 'Task'), ('NOT', 'Not Categorized')], default='NOT', max_length=16, verbose_name='Issue Type')),
                ('state', models.CharField(choices=[('OPN', 'Open'), ('BLK', 'Blocked'), ('MRG', 'Merged'), ('RES', 'Resolved'), ('CLS', 'Closed')], default='OPN', max_length=16, verbose_name='State')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('other_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('body', models.TextField(max_length=1000, verbose_name='Body')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
